import JavaScriptLogo from '../../../../public/logo/JavaScript.png';
import ReactLogo from '../../../../public/logo/react.png';
import NextjsLogo from '../../../../public/logo/Next.js.png';
import CssLogo from '../../../../public/logo/css.png';
import TailwindLogo from '../../../../public/logo/TailwindCSS.png';
import MaterialUILogo from '../../../../public/logo/Material UI.png';
import AccerdityLogo from '../../../../public/logo/accerdity.png';
import ExpressLogo from '../../../../public/logo/Express.png';
import NodejsLogo from '../../../../public/logo/Node.js.png';
import MongoDBLogo from '../../../../public/logo/MongoDB.png';
import SQLLogo from '../../../../public/logo/SQL Developer.png';
import MySQLLogo from '../../../../public/logo/MySQL.png';
import PythonLogo from '../../../../public/logo/Python.png';
import PyTorchLogo from '../../../../public/logo/pytorch.png';
import TensorFlowLogo from '../../../../public/logo/TensorFlow.png';
import ScikitLearnLogo from '../../../../public/logo/scikit-learn.png';
import LangChainLogo from '../../../../public/logo/langchain.jpeg';
import HuggingFaceLogo from '../../../../public/logo/huggingface.png';
import WeaviateLogo from '../../../../public/logo/weaviate.svg';
import Neo4jLogo from '../../../../public/logo/neo4j.svg';
import AWSLogo from '../../../../public/logo/aws.png';
import DockerLogo from '../../../../public/logo/docker.svg';
import MLFlowLogo from '../../../../public/logo/mlflow.jpeg';
import CPlusPlusLogo from '../../../../public/logo/C++ (CPlusPlus).png';
import JavaLogo from '../../../../public/logo/Java.png';

export const sourcelist1 = [ReactLogo, NextjsLogo];
export const sourcelist2 = [CssLogo, TailwindLogo, MaterialUILogo, AccerdityLogo];
export const sourcelist3 = [ExpressLogo, NodejsLogo];
export const sourcelist4 = [MongoDBLogo, SQLLogo, MySQLLogo];
export const sourcelist5 = [PythonLogo, JavaScriptLogo, CPlusPlusLogo, JavaLogo];
export const sourcelist6 = [PyTorchLogo, TensorFlowLogo, ScikitLearnLogo];
export const sourcelist7 = [LangChainLogo, HuggingFaceLogo];
export const sourcelist8 = [WeaviateLogo, Neo4jLogo];
export const sourcelist9 = [AWSLogo, DockerLogo, MLFlowLogo];